package io.smnp.dsl.token.model.enumeration

enum class TokenType(val token: String) {
    NONE("<NONE>"),
    RELATION("==, !=, >=, <="),
    DOUBLE_ASTERISK("**"),
    DOUBLE_PIPE("||"),
    OPEN_CURLY("{"),
    CLOSE_CURLY("}"),
    OPEN_PAREN("("),
    CLOSE_PAREN(")"),
    OPEN_SQUARE("["),
    CLOSE_SQUARE("]"),
    OPEN_ANGLE("<"),
    CLOSE_ANGLE(">"),
    SEMICOLON(";"),
    ASTERISK("*"),
    PERCENT("%"),
    DOLLAR("$"),
    ASSIGN("="),
    ARROW("->"),
    COLON(":"),
    COMMA(","),
    SLASH("/"),
    MINUS("-"),
    PLUS("+"),
    CARET("^"),
    DOTS("..."),
    PIPE("|"),
    AMP("&"),
    DOT("."),
    AND("and"),
    OR("or"),
    NOT("not"),
    INTEGER("integer"),
    STRING("string"),
    FLOAT("float"),
    NOTE("note"),
    BOOL("bool"),
    TYPE("type"),
    FUNCTION("function"),
    RETURN("return"),
    EXTEND("extend"),
    IMPORT("import"),
    THROW("throw"),
    FROM("from"),
    WITH("with"),
    ELSE("else"),
    IF("if"),
    AS("as"),
    IDENTIFIER("identifier"),
    COMMENT("comment");

    override fun toString(): String {
        return super.name.toLowerCase()
    }
}